enabled: true
production-mode: true
custom_logo:
  user/themes/images/logo/avatar.png:
    name: avatar.png
    type: image/png
    size: 38720
    path: user/themes/images/logo/avatar.png
custom_logo_mobile:
  user/themes/images/logo/avatar.png:
    name: avatar.png
    type: image/png
    size: 38720
    path: user/themes/images/logo/avatar.png
