name: Deploy to Production

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy code to prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy
      uses: musps/action-deployer-php@master
      with:
        args: deploy prod -f .github/deploy.php
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}